config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: {minimum: 6 }
  validates :movie, uniqueness: {
    scope: :list,
    message: 'The movie can join the list only one time'
  }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def new
  #   @bookmark = Bookmark.new
  #   @list = List.find(params[:list_id])
  # end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    # @movie = Movie.find(params[:movie_id]) # Avec ces deux lignes ça ne marchait, pas
    # @bookmark.movie = @movie # Pas sûr de comprendre pourquoi!
    # raise
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id]) # Attention ici ce n'est pas les strong_params qu'on appelle!
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy

  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form_new.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.association :movie, input_html: {multiple: true, data: {controller: "tom-select", tom_select_options_value: {tags: true}}} %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/new.html.erb
<%= render partial: 'form_new', locals: {list: @list, bookmark: @bookmark}  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsNewWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://unpkg.com/typed.js@2.0.14/dist/typed.umd.js"></script>


  </head>

  <body>
    <div id="typed-strings">
     <p>Typed.js is a <strong>JavaScript</strong> library.</p>
     <p>It <em>types</em> out sentences.</p>
    </div>
    <span id="typed"></span>

    <%= yield %>

    <script>
      var typed = new Typed('#typed', {
       stringsElement: '#typed-strings'
      });
    </script>
  </body>
</html>

app/views/lists/index.html.erb
<p>hello</p>


<% @lists.each do |list| %>
  <%= link_to list_path(list) do  %>
    <p><%= list.name %></p>
  <% end %>

<% end %>

<%= link_to "Add a new list", new_list_path %>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<p>Please find here all the movies of this list</p>

<%#= link_to "Add a new film to this list", new_list_bookmark_path(@list)  %>

<% @list.bookmarks.each do |bookmark| %>
  <ol>
  <li>
    <ul>
      <li><%= bookmark.movie.title %> </li>
      <li><%= bookmark.movie.overview %></li>
      <li><%= bookmark.movie.rating %></li>
      <li><%= bookmark.comment %></li>
      <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-solid fa-circle-xmark remove"></i>
              <% end %>

    </ul>
  </li>
  </ol>
<% end %>


<br><br><br>

<%= render partial: 'bookmarks/form_new', locals: {list: @list, bookmark: @bookmark}  %>

<br><br><br><br><br>
<%= link_to "return to all the lists", lists_path  %>


 <%#= link_to "Delete",
    review_path(review),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>